# Generated by Django 5.1.1 on 2024-09-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
