# Generated by Django 5.1.1 on 2024-09-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_alter_blogentry_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogEntry',
            new_name='BlogPost',
        ),
    ]
